#![allow(non_upper_case_globals)]

pub use tsox_core::diagnostics::messages_generated::*;

pub use tsox_core::diagnostics::messages_generated::X_CONSTRUCTOR_IS_A_RESERVED_WORD as X_constructor_is_a_reserved_word;
pub use tsox_core::diagnostics::messages_generated::X_DELETE_CANNOT_BE_CALLED_ON_AN_IDENTIFIER_IN_STRICT_MODE as X_delete_cannot_be_called_on_an_identifier_in_strict_mode;
pub use tsox_core::diagnostics::messages_generated::A_LABEL_IS_NOT_ALLOWED_HERE as A_label_is_not_allowed_here;
pub use tsox_core::diagnostics::messages_generated::X_WITH_STATEMENTS_ARE_NOT_ALLOWED_IN_STRICT_MODE as X_with_statements_are_not_allowed_in_strict_mode;
pub use tsox_core::diagnostics::messages_generated::CANNOT_REDECLARE_BLOCK_SCOPED_VARIABLE_0 as Cannot_redeclare_block_scoped_variable_0;
pub use tsox_core::diagnostics::messages_generated::DUPLICATE_IDENTIFIER_0 as Duplicate_identifier_0;
pub use tsox_core::diagnostics::messages_generated::ENUM_DECLARATIONS_CAN_ONLY_MERGE_WITH_NAMESPACE_OR_OTHER_ENUM_DECLARATIONS as Enum_declarations_can_only_merge_with_namespace_or_other_enum_declarations;
pub use tsox_core::diagnostics::messages_generated::A_MODULE_CANNOT_HAVE_MULTIPLE_DEFAULT_EXPORTS as A_module_cannot_have_multiple_default_exports;
pub use tsox_core::diagnostics::messages_generated::ANOTHER_EXPORT_DEFAULT_IS_HERE as Another_export_default_is_here;
pub use tsox_core::diagnostics::messages_generated::X_AND_HERE as X_and_here;
pub use tsox_core::diagnostics::messages_generated::FUNCTION_DECLARATIONS_ARE_NOT_ALLOWED_INSIDE_BLOCKS_IN_STRICT_MODE_WHEN_TARGETING_ES5_CLASS_DEFINITIONS_ARE_AUTOMATICALLY_IN_STRICT_MODE as Function_declarations_are_not_allowed_inside_blocks_in_strict_mode_when_targeting_ES5_Class_definitions_are_automatically_in_strict_mode;
pub use tsox_core::diagnostics::messages_generated::FUNCTION_DECLARATIONS_ARE_NOT_ALLOWED_INSIDE_BLOCKS_IN_STRICT_MODE_WHEN_TARGETING_ES5_MODULES_ARE_AUTOMATICALLY_IN_STRICT_MODE as Function_declarations_are_not_allowed_inside_blocks_in_strict_mode_when_targeting_ES5_Modules_are_automatically_in_strict_mode;
pub use tsox_core::diagnostics::messages_generated::FUNCTION_DECLARATIONS_ARE_NOT_ALLOWED_INSIDE_BLOCKS_IN_STRICT_MODE_WHEN_TARGETING_ES5 as Function_declarations_are_not_allowed_inside_blocks_in_strict_mode_when_targeting_ES5;
pub use tsox_core::diagnostics::messages_generated::IDENTIFIER_EXPECTED_0_IS_A_RESERVED_WORD_IN_STRICT_MODE_CLASS_DEFINITIONS_ARE_AUTOMATICALLY_IN_STRICT_MODE as Identifier_expected_0_is_a_reserved_word_in_strict_mode_Class_definitions_are_automatically_in_strict_mode;
pub use tsox_core::diagnostics::messages_generated::IDENTIFIER_EXPECTED_0_IS_A_RESERVED_WORD_IN_STRICT_MODE_MODULES_ARE_AUTOMATICALLY_IN_STRICT_MODE as Identifier_expected_0_is_a_reserved_word_in_strict_mode_Modules_are_automatically_in_strict_mode;
pub use tsox_core::diagnostics::messages_generated::IDENTIFIER_EXPECTED_0_IS_A_RESERVED_WORD_IN_STRICT_MODE as Identifier_expected_0_is_a_reserved_word_in_strict_mode;
