//! Build script.
//!
//! Bundles the `lib.*.d.ts` files into the binary by copying them from the
//! sibling Go project (`../typescript-rust/internal/bundled/libs`) into
//! `OUT_DIR` and generating a Rust module that exposes them via
//! `include_str!`. This mirrors Go's `go:embed` of `internal/bundled/libs`.
//!
//! When the port is far enough along that the `.d.ts` files live inside this
//! crate, point `libs_source_dir` at the local directory instead.

use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());

    // Source of the bundled lib files: the Go project's libs directory.
    // Fall back to a local `bundled/libs` directory if present.
    let go_libs_dir = manifest_dir.join("../typescript-rust/internal/bundled/libs");
    let local_libs_dir = manifest_dir.join("bundled/libs");
    let libs_source_dir: PathBuf = if go_libs_dir.is_dir() {
        go_libs_dir.canonicalize().unwrap_or(go_libs_dir)
    } else if local_libs_dir.is_dir() {
        local_libs_dir.canonicalize().unwrap_or(local_libs_dir)
    } else {
        // No bundled libs available; emit an empty manifest so the build still
        // succeeds (the CLI will simply have no built-in lib files).
        let gen_path = out_dir.join("bundled_libs.rs");
        fs::write(
            &gen_path,
            "/// Bundled lib files (none available at build time).\n\
             pub fn bundled_libs() -> &'static [(&'static str, &'static str)] { &[] }\n",
        )
        .unwrap();
        println!("cargo:rustc-cfg=bundled_libs_empty");
        return;
    };

    let dest_libs_dir = out_dir.join("bundled_libs");
    fs::create_dir_all(&dest_libs_dir).unwrap();

    let mut entries: Vec<(String, PathBuf)> = Vec::new();
    for entry in fs::read_dir(&libs_source_dir).unwrap().flatten() {
        let path = entry.path();
        if path.extension().and_then(|e| e.to_str()) == Some("ts") {
            let name = path
                .file_name()
                .and_then(|n| n.to_str())
                .unwrap()
                .to_string();
            let dest = dest_libs_dir.join(&name);
            fs::copy(&path, &dest).unwrap();
            entries.push((name, dest));
        }
    }
    entries.sort_by(|a, b| a.0.cmp(&b.0));

    // Generate a Rust file in OUT_DIR that includes each lib via include_str!.
    // The include_str! paths are relative to the generated file's location
    // (OUT_DIR), so we use "bundled_libs/<name>".
    let mut src = String::new();
    src.push_str("/// Bundled `lib.*.d.ts` files, generated by build.rs.\n");
    src.push_str("pub fn bundled_libs() -> &'static [(&'static str, &'static str)] {\n    &[\n");
    for (name, _) in &entries {
        src.push_str(&format!(
            "        (\"{name}\", include_str!(\"bundled_libs/{name}\")),\n"
        ));
    }
    src.push_str("    ]\n}\n");

    let gen_path = out_dir.join("bundled_libs.rs");
    fs::write(&gen_path, src).unwrap();

    // Re-run if the source libs directory changes.
    println!("cargo:rerun-if-changed={}", libs_source_dir.display());
}
