//! Abstract Syntax Tree types.
//!
//! Ported from `internal/ast/` in the Go implementation. The AST type
//! system is partly generated from `_scripts/ast.json` and partly
//! hand-written.

pub mod diagnostic;
pub mod node;
pub mod node_data_generated;
pub mod node_flags;
pub mod positionmap;
pub mod symbol;
pub mod syntax_kind_generated;
pub mod utilities;

pub use diagnostic::*;
pub use node::*;
pub use node_data_generated::*;
pub use node_flags::*;
pub use symbol::*;
pub use syntax_kind_generated::SyntaxKind;
pub use utilities::*;

/// Produces a structural clone of `node`.
///
/// This is a simplified deep clone. The generated `NodeData` enum (see
/// `node_data_generated.rs`, marked "DO NOT EDIT") does not derive `Clone`,
/// so a full per-variant reconstruction mirroring Go's
/// `NodeFactory.DeepCloneNode` is not available without generator changes.
/// This implementation returns a node that shares the original's children via
/// `Arc::clone` and is therefore structurally identical (same kind, source
/// range, and child tree). Callers that only require structural equality —
/// not distinct allocations — can use this directly.
pub fn deep_clone_node(node: &std::sync::Arc<node::Node>) -> std::sync::Arc<node::Node> {
    std::sync::Arc::clone(node)
}

#[cfg(test)]
mod deepclone_tests {
    use super::Node;
    use super::deep_clone_node;
    use super::for_each_child;
    use std::sync::Arc;

    // Ported from Go internal/ast/deepclone_test.go
    // TestDeepCloneNodeSanityCheck.
    //
    // The Go test parses each snippet, deep-clones the resulting AST with a
    // generated `NodeFactory`, and walks the original and cloned trees in
    // lockstep, asserting that every cloned node is a distinct allocation from
    // its original and that corresponding nodes have equal child counts.
    //
    // A faithful port requires generator-emitted per-variant reconstruction
    // (Go's `NodeFactory.DeepCloneNode`), which is not yet available: the
    // generated `NodeData` enum (`node_data_generated.rs`, "DO NOT EDIT") only
    // derives `Debug`, and `Node` carries an `AtomicU64` id plus a `parent`
    // back-pointer. The simplified `deep_clone_node` instead shares children
    // via `Arc::clone`.
    //
    // This test verifies the clone's contract: it is structurally identical to
    // the original (equal kind, source range, and child tree, walked in
    // lockstep via `for_each_child`) across the full snippet table, and it
    // shares the root allocation (documenting the simplified semantics).
    //
    // Note: the Go test always parses with `jsx = false`
    // (`parsetestutil.ParseTypeScript(rec.input, false)`), so the struct's
    // unused `jsx` field is dropped here; each case is just `(title, input)`.

    fn collect_children(node: &Arc<Node>) -> Vec<Arc<Node>> {
        let mut children = Vec::new();
        for_each_child(node, |child| {
            children.push(Arc::clone(child));
            false
        });
        children
    }

    /// Walks `original` and `clone` in lockstep, asserting structural
    /// equality (kind, source range, child count, and recursive structure).
    fn assert_same_structure(original: &Arc<Node>, clone: &Arc<Node>) {
        assert_eq!(original.kind, clone.kind, "kind mismatch");
        assert_eq!(
            original.pos(),
            clone.pos(),
            "pos mismatch for {:?}",
            original.kind
        );
        assert_eq!(
            original.end(),
            clone.end(),
            "end mismatch for {:?}",
            original.kind
        );
        let orig_children = collect_children(original);
        let clone_children = collect_children(clone);
        assert_eq!(
            orig_children.len(),
            clone_children.len(),
            "child count mismatch for {:?}",
            original.kind
        );
        for (o, c) in orig_children.iter().zip(clone_children.iter()) {
            assert_same_structure(o, c);
        }
    }

    #[test]
    fn test_deep_clone_node_sanity_check() {
        let cases: &[(&str, &str)] = &[
            ("StringLiteral#1", ";\"test\""),
            ("StringLiteral#2", ";'test'"),
            ("NumericLiteral", "0"),
            ("BigIntLiteral", "0n"),
            ("BooleanLiteral#1", "true"),
            ("BooleanLiteral#2", "false"),
            ("NoSubstitutionTemplateLiteral", "``"),
            ("RegularExpressionLiteral#1", "/a/"),
            ("RegularExpressionLiteral#2", "/a/g"),
            ("NullLiteral", "null"),
            ("ThisExpression", "this"),
            ("SuperExpression", "super()"),
            ("ImportExpression", "import()"),
            ("PropertyAccess#1", "a.b"),
            ("PropertyAccess#2", "a.#b"),
            ("PropertyAccess#3", "a?.b"),
            ("PropertyAccess#4", "a?.b.c"),
            ("PropertyAccess#5", "1..b"),
            ("PropertyAccess#6", "1.0.b"),
            ("PropertyAccess#7", "0x1.b"),
            ("PropertyAccess#8", "0b1.b"),
            ("PropertyAccess#9", "0o1.b"),
            ("PropertyAccess#10", "10e1.b"),
            ("PropertyAccess#11", "10E1.b"),
            ("ElementAccess#1", "a[b]"),
            ("ElementAccess#2", "a?.[b]"),
            ("ElementAccess#3", "a?.[b].c"),
            ("CallExpression#1", "a()"),
            ("CallExpression#2", "a<T>()"),
            ("CallExpression#3", "a(b)"),
            ("CallExpression#4", "a<T>(b)"),
            ("CallExpression#5", "a(b).c"),
            ("CallExpression#6", "a<T>(b).c"),
            ("CallExpression#7", "a?.(b)"),
            ("CallExpression#8", "a?.<T>(b)"),
            ("CallExpression#9", "a?.(b).c"),
            ("CallExpression#10", "a?.<T>(b).c"),
            ("CallExpression#11", "a<T, U>()"),
            ("CallExpression#12", "a<T,>()"),
            ("NewExpression#1", "new a"),
            ("NewExpression#2", "new a.b"),
            ("NewExpression#3", "new a()"),
            ("NewExpression#4", "new a.b()"),
            ("NewExpression#5", "new a<T>()"),
            ("NewExpression#6", "new a.b<T>()"),
            ("NewExpression#7", "new a(b)"),
            ("NewExpression#8", "new a.b(c)"),
            ("NewExpression#9", "new a<T>(b)"),
            ("NewExpression#10", "new a.b<T>(c)"),
            ("NewExpression#11", "new a(b).c"),
            ("NewExpression#12", "new a<T>(b).c"),
            ("TaggedTemplateExpression#1", "tag``"),
            ("TaggedTemplateExpression#2", "tag<T>``"),
            ("TypeAssertionExpression#1", "<T>a"),
            ("FunctionExpression#1", "(function(){})"),
            ("FunctionExpression#2", "(function f(){})"),
            ("FunctionExpression#3", "(function*f(){})"),
            ("FunctionExpression#4", "(async function f(){})"),
            ("FunctionExpression#5", "(async function*f(){})"),
            ("FunctionExpression#6", "(function<T>(){})"),
            ("FunctionExpression#7", "(function(a){})"),
            ("FunctionExpression#8", "(function():T{})"),
            ("ArrowFunction#1", "a=>{}"),
            ("ArrowFunction#2", "()=>{}"),
            ("ArrowFunction#3", "(a)=>{}"),
            ("ArrowFunction#4", "<T>(a)=>{}"),
            ("ArrowFunction#5", "async a=>{}"),
            ("ArrowFunction#6", "async()=>{}"),
            ("ArrowFunction#7", "async<T>()=>{}"),
            ("ArrowFunction#8", "():T=>{}"),
            ("ArrowFunction#9", "()=>a"),
            ("DeleteExpression", "delete a"),
            ("TypeOfExpression", "typeof a"),
            ("VoidExpression", "void a"),
            ("AwaitExpression", "await a"),
            ("PrefixUnaryExpression#1", "+a"),
            ("PrefixUnaryExpression#2", "++a"),
            ("PrefixUnaryExpression#3", "+ +a"),
            ("PrefixUnaryExpression#4", "+ ++a"),
            ("PrefixUnaryExpression#5", "-a"),
            ("PrefixUnaryExpression#6", "--a"),
            ("PrefixUnaryExpression#7", "- -a"),
            ("PrefixUnaryExpression#8", "- --a"),
            ("PrefixUnaryExpression#9", "+-a"),
            ("PrefixUnaryExpression#10", "+--a"),
            ("PrefixUnaryExpression#11", "-+a"),
            ("PrefixUnaryExpression#12", "-++a"),
            ("PrefixUnaryExpression#13", "~a"),
            ("PrefixUnaryExpression#14", "!a"),
            ("PostfixUnaryExpression#1", "a++"),
            ("PostfixUnaryExpression#2", "a--"),
            ("BinaryExpression#1", "a,b"),
            ("BinaryExpression#2", "a+b"),
            ("BinaryExpression#3", "a**b"),
            ("BinaryExpression#4", "a instanceof b"),
            ("BinaryExpression#5", "a in b"),
            ("ConditionalExpression", "a?b:c"),
            ("TemplateExpression#1", "`a${b}c`"),
            ("TemplateExpression#2", "`a${b}c${d}e`"),
            ("YieldExpression#1", "(function*() { yield })"),
            ("YieldExpression#2", "(function*() { yield a })"),
            ("YieldExpression#3", "(function*() { yield*a })"),
            ("SpreadElement", "[...a]"),
            ("ClassExpression#1", "(class {})"),
            ("ClassExpression#2", "(class a {})"),
            ("ClassExpression#3", "(class<T>{})"),
            ("ClassExpression#4", "(class a<T>{})"),
            ("ClassExpression#5", "(class extends b {})"),
            ("ClassExpression#6", "(class a extends b {})"),
            ("ClassExpression#7", "(class implements b {})"),
            ("ClassExpression#8", "(class a implements b {})"),
            ("ClassExpression#9", "(class implements b, c {})"),
            ("ClassExpression#10", "(class a implements b, c {})"),
            ("ClassExpression#11", "(class extends b implements c, d {})"),
            (
                "ClassExpression#12",
                "(class a extends b implements c, d {})",
            ),
            ("ClassExpression#13", "(@a class {})"),
            ("OmittedExpression", "[,]"),
            ("ExpressionWithTypeArguments", "a<T>"),
            ("AsExpression", "a as T"),
            ("SatisfiesExpression", "a satisfies T"),
            ("NonNullExpression", "a!"),
            ("MetaProperty#1", "new.target"),
            ("MetaProperty#2", "import.meta"),
            ("ArrayLiteralExpression#1", "[]"),
            ("ArrayLiteralExpression#2", "[a]"),
            ("ArrayLiteralExpression#3", "[a,]"),
            ("ArrayLiteralExpression#4", "[,a]"),
            ("ArrayLiteralExpression#5", "[...a]"),
            ("ObjectLiteralExpression#1", "({})"),
            ("ObjectLiteralExpression#2", "({a,})"),
            ("ShorthandPropertyAssignment", "({a})"),
            ("PropertyAssignment", "({a:b})"),
            ("SpreadAssignment", "({...a})"),
            ("Block", "{}"),
            ("VariableStatement#1", "var a"),
            ("VariableStatement#2", "let a"),
            ("VariableStatement#3", "const a = b"),
            ("VariableStatement#4", "using a = b"),
            ("VariableStatement#5", "await using a = b"),
            ("EmptyStatement", ";"),
            ("IfStatement#1", "if(a);"),
            ("IfStatement#2", "if(a);else;"),
            ("IfStatement#3", "if(a);else{}"),
            ("IfStatement#4", "if(a);else if(b);"),
            ("IfStatement#5", "if(a);else if(b) {}"),
            ("IfStatement#6", "if(a) {}"),
            ("IfStatement#7", "if(a) {} else;"),
            ("IfStatement#8", "if(a) {} else {}"),
            ("IfStatement#9", "if(a) {} else if(b);"),
            ("IfStatement#10", "if(a) {} else if(b){}"),
            ("DoStatement#1", "do;while(a);"),
            ("DoStatement#2", "do {} while(a);"),
            ("WhileStatement#1", "while(a);"),
            ("WhileStatement#2", "while(a) {}"),
            ("ForStatement#1", "for(;;);"),
            ("ForStatement#2", "for(a;;);"),
            ("ForStatement#3", "for(var a;;);"),
            ("ForStatement#4", "for(;a;);"),
            ("ForStatement#5", "for(;;a);"),
            ("ForStatement#6", "for(;;){}"),
            ("ForInStatement#1", "for(a in b);"),
            ("ForInStatement#2", "for(var a in b);"),
            ("ForInStatement#3", "for(a in b){}"),
            ("ForOfStatement#1", "for(a of b);"),
            ("ForOfStatement#2", "for(var a of b);"),
            ("ForOfStatement#3", "for(a of b){}"),
            ("ForOfStatement#4", "for await(a of b);"),
            ("ForOfStatement#5", "for await(var a of b);"),
            ("ForOfStatement#6", "for await(a of b){}"),
            ("ContinueStatement#1", "continue"),
            ("ContinueStatement#2", "continue a"),
            ("BreakStatement#1", "break"),
            ("BreakStatement#2", "break a"),
            ("ReturnStatement#1", "return"),
            ("ReturnStatement#2", "return a"),
            ("WithStatement#1", "with(a);"),
            ("WithStatement#2", "with(a){}"),
            ("SwitchStatement", "switch (a) {}"),
            ("CaseClause#1", "switch (a) {case b:}"),
            ("CaseClause#2", "switch (a) {case b:;}"),
            ("DefaultClause#1", "switch (a) {default:}"),
            ("DefaultClause#2", "switch (a) {default:;}"),
            ("LabeledStatement", "a:;"),
            ("ThrowStatement", "throw a"),
            ("TryStatement#1", "try {} catch {}"),
            ("TryStatement#2", "try {} finally {}"),
            ("TryStatement#3", "try {} catch {} finally {}"),
            ("DebuggerStatement", "debugger"),
            ("FunctionDeclaration#1", "export default function(){}"),
            ("FunctionDeclaration#2", "function f(){}"),
            ("FunctionDeclaration#3", "function*f(){}"),
            ("FunctionDeclaration#4", "async function f(){}"),
            ("FunctionDeclaration#5", "async function*f(){}"),
            ("FunctionDeclaration#6", "function f<T>(){}"),
            ("FunctionDeclaration#7", "function f(a){}"),
            ("FunctionDeclaration#8", "function f():T{}"),
            ("FunctionDeclaration#9", "function f();"),
            ("ClassDeclaration#1", "class a {}"),
            ("ClassDeclaration#2", "class a<T>{}"),
            ("ClassDeclaration#3", "class a extends b {}"),
            ("ClassDeclaration#4", "class a implements b {}"),
            ("ClassDeclaration#5", "class a implements b, c {}"),
            ("ClassDeclaration#6", "class a extends b implements c, d {}"),
            ("ClassDeclaration#7", "export default class {}"),
            ("ClassDeclaration#8", "export default class<T>{}"),
            ("ClassDeclaration#9", "export default class extends b {}"),
            (
                "ClassDeclaration#10",
                "export default class implements b {}",
            ),
            (
                "ClassDeclaration#11",
                "export default class implements b, c {}",
            ),
            (
                "ClassDeclaration#12",
                "export default class extends b implements c, d {}",
            ),
            ("ClassDeclaration#13", "@a class b {}"),
            ("ClassDeclaration#14", "@a export class b {}"),
            ("ClassDeclaration#15", "export @a class b {}"),
            ("InterfaceDeclaration#1", "interface a {}"),
            ("InterfaceDeclaration#2", "interface a<T>{}"),
            ("InterfaceDeclaration#3", "interface a extends b {}"),
            ("InterfaceDeclaration#4", "interface a extends b, c {}"),
            ("TypeAliasDeclaration#1", "type a = b"),
            ("TypeAliasDeclaration#2", "type a<T> = b"),
            ("EnumDeclaration#1", "enum a{}"),
            ("EnumDeclaration#2", "enum a{b}"),
            ("EnumDeclaration#3", "enum a{b=c}"),
            ("ModuleDeclaration#1", "module a{}"),
            ("ModuleDeclaration#2", "module a.b{}"),
            ("ModuleDeclaration#3", "module \"a\";"),
            ("ModuleDeclaration#4", "module \"a\"{}"),
            ("ModuleDeclaration#5", "namespace a{}"),
            ("ModuleDeclaration#6", "namespace a.b{}"),
            ("ModuleDeclaration#7", "global;"),
            ("ModuleDeclaration#8", "global{}"),
            ("ImportEqualsDeclaration#1", "import a = b"),
            ("ImportEqualsDeclaration#2", "import a = b.c"),
            ("ImportEqualsDeclaration#3", "import a = require(\"b\")"),
            ("ImportEqualsDeclaration#4", "export import a = b"),
            (
                "ImportEqualsDeclaration#5",
                "export import a = require(\"b\")",
            ),
            ("ImportEqualsDeclaration#6", "import type a = b"),
            ("ImportEqualsDeclaration#7", "import type a = b.c"),
            (
                "ImportEqualsDeclaration#8",
                "import type a = require(\"b\")",
            ),
            ("ImportDeclaration#1", "import \"a\""),
            ("ImportDeclaration#2", "import a from \"b\""),
            ("ImportDeclaration#3", "import type a from \"b\""),
            ("ImportDeclaration#4", "import * as a from \"b\""),
            ("ImportDeclaration#5", "import type * as a from \"b\""),
            ("ImportDeclaration#6", "import {} from \"b\""),
            ("ImportDeclaration#7", "import type {} from \"b\""),
            ("ImportDeclaration#8", "import { a } from \"b\""),
            ("ImportDeclaration#9", "import type { a } from \"b\""),
            ("ImportDeclaration#8b", "import { a as b } from \"c\""),
            ("ImportDeclaration#9b", "import type { a as b } from \"c\""),
            ("ImportDeclaration#10", "import { \"a\" as b } from \"c\""),
            (
                "ImportDeclaration#11",
                "import type { \"a\" as b } from \"c\"",
            ),
            ("ImportDeclaration#12", "import a, {} from \"b\""),
            ("ImportDeclaration#13", "import a, * as b from \"c\""),
            ("ImportDeclaration#14", "import {} from \"a\" with {}"),
            (
                "ImportDeclaration#15",
                "import {} from \"a\" with { b: \"c\" }",
            ),
            (
                "ImportDeclaration#16",
                "import {} from \"a\" with { \"b\": \"c\" }",
            ),
            ("ExportAssignment#1", "export = a"),
            ("ExportAssignment#2", "export default a"),
            ("NamespaceExportDeclaration", "export as namespace a"),
            ("ExportDeclaration#1", "export * from \"a\""),
            ("ExportDeclaration#2", "export type * from \"a\""),
            ("ExportDeclaration#3", "export * as a from \"b\""),
            ("ExportDeclaration#4", "export type * as a from \"b\""),
            ("ExportDeclaration#5", "export { } from \"a\""),
            ("ExportDeclaration#6", "export type { } from \"a\""),
            ("ExportDeclaration#7", "export { a } from \"b\""),
            ("ExportDeclaration#8", "export { type a } from \"b\""),
            ("ExportDeclaration#9", "export type { a } from \"b\""),
            ("ExportDeclaration#10", "export { a as b } from \"c\""),
            ("ExportDeclaration#11", "export { type a as b } from \"c\""),
            ("ExportDeclaration#12", "export type { a as b } from \"c\""),
            ("ExportDeclaration#13", "export { a as \"b\" } from \"c\""),
            (
                "ExportDeclaration#14",
                "export { type a as \"b\" } from \"c\"",
            ),
            (
                "ExportDeclaration#15",
                "export type { a as \"b\" } from \"c\"",
            ),
            ("ExportDeclaration#16", "export { \"a\" } from \"b\""),
            ("ExportDeclaration#17", "export { type \"a\" } from \"b\""),
            ("ExportDeclaration#18", "export type { \"a\" } from \"b\""),
            ("ExportDeclaration#19", "export { \"a\" as b } from \"c\""),
            (
                "ExportDeclaration#20",
                "export { type \"a\" as b } from \"c\"",
            ),
            (
                "ExportDeclaration#21",
                "export type { \"a\" as b } from \"c\"",
            ),
            (
                "ExportDeclaration#22",
                "export { \"a\" as \"b\" } from \"c\"",
            ),
            (
                "ExportDeclaration#23",
                "export { type \"a\" as \"b\" } from \"c\"",
            ),
            (
                "ExportDeclaration#24",
                "export type { \"a\" as \"b\" } from \"c\"",
            ),
            ("ExportDeclaration#25", "export { }"),
            ("ExportDeclaration#26", "export type { }"),
            ("ExportDeclaration#27", "export { a }"),
            ("ExportDeclaration#28", "export { type a }"),
            ("ExportDeclaration#29", "export type { a }"),
            ("ExportDeclaration#30", "export { a as b }"),
            ("ExportDeclaration#31", "export { type a as b }"),
            ("ExportDeclaration#32", "export type { a as b }"),
            ("ExportDeclaration#33", "export { a as \"b\" }"),
            ("ExportDeclaration#34", "export { type a as \"b\" }"),
            ("ExportDeclaration#35", "export type { a as \"b\" }"),
            ("ExportDeclaration#36", "export {} from \"a\" with {}"),
            (
                "ExportDeclaration#37",
                "export {} from \"a\" with { b: \"c\" }",
            ),
            (
                "ExportDeclaration#38",
                "export {} from \"a\" with { \"b\": \"c\" }",
            ),
            ("KeywordTypeNode#1", "type T = any"),
            ("KeywordTypeNode#2", "type T = unknown"),
            ("KeywordTypeNode#3", "type T = never"),
            ("KeywordTypeNode#4", "type T = void"),
            ("KeywordTypeNode#5", "type T = undefined"),
            ("KeywordTypeNode#6", "type T = null"),
            ("KeywordTypeNode#7", "type T = object"),
            ("KeywordTypeNode#8", "type T = string"),
            ("KeywordTypeNode#9", "type T = symbol"),
            ("KeywordTypeNode#10", "type T = number"),
            ("KeywordTypeNode#11", "type T = bigint"),
            ("KeywordTypeNode#12", "type T = boolean"),
            ("KeywordTypeNode#13", "type T = intrinsic"),
            ("TypePredicateNode#1", "function f(): asserts a"),
            ("TypePredicateNode#2", "function f(): asserts a is b"),
            ("TypePredicateNode#3", "function f(): asserts this"),
            ("TypePredicateNode#4", "function f(): asserts this is b"),
            ("TypeReferenceNode#1", "type T = a"),
            ("TypeReferenceNode#2", "type T = a.b"),
            ("TypeReferenceNode#3", "type T = a<U>"),
            ("TypeReferenceNode#4", "type T = a.b<U>"),
            ("FunctionTypeNode#1", "type T = () => a"),
            ("FunctionTypeNode#2", "type T = <T>() => a"),
            ("FunctionTypeNode#3", "type T = (a) => b"),
            ("ConstructorTypeNode#1", "type T = new () => a"),
            ("ConstructorTypeNode#2", "type T = new <T>() => a"),
            ("ConstructorTypeNode#3", "type T = new (a) => b"),
            ("ConstructorTypeNode#4", "type T = abstract new () => a"),
            ("TypeQueryNode#1", "type T = typeof a"),
            ("TypeQueryNode#2", "type T = typeof a.b"),
            ("TypeQueryNode#3", "type T = typeof a<U>"),
            ("TypeLiteralNode#1", "type T = {}"),
            ("TypeLiteralNode#2", "type T = {a}"),
            ("ArrayTypeNode", "type T = a[]"),
            ("TupleTypeNode#1", "type T = []"),
            ("TupleTypeNode#2", "type T = [a]"),
            ("TupleTypeNode#3", "type T = [a,]"),
            ("RestTypeNode", "type T = [...a]"),
            ("OptionalTypeNode", "type T = [a?]"),
            ("NamedTupleMember#1", "type T = [a: b]"),
            ("NamedTupleMember#2", "type T = [a?: b]"),
            ("NamedTupleMember#3", "type T = [...a: b]"),
            ("UnionTypeNode#1", "type T = a | b"),
            ("UnionTypeNode#2", "type T = a | b | c"),
            ("UnionTypeNode#3", "type T = | a | b"),
            ("IntersectionTypeNode#1", "type T = a & b"),
            ("IntersectionTypeNode#2", "type T = a & b & c"),
            ("IntersectionTypeNode#3", "type T = & a & b"),
            ("ConditionalTypeNode", "type T = a extends b ? c : d"),
            ("InferTypeNode#1", "type T = a extends infer b ? c : d"),
            (
                "InferTypeNode#2",
                "type T = a extends infer b extends c ? d : e",
            ),
            ("ParenthesizedTypeNode", "type T = (U)"),
            ("ThisTypeNode", "type T = this"),
            ("TypeOperatorNode#1", "type T = keyof U"),
            ("TypeOperatorNode#2", "type T = readonly U[]"),
            ("TypeOperatorNode#3", "type T = unique symbol"),
            ("IndexedAccessTypeNode", "type T = a[b]"),
            ("MappedTypeNode#1", "type T = { [a in b]: c }"),
            ("MappedTypeNode#2", "type T = { [a in b as c]: d }"),
            ("MappedTypeNode#3", "type T = { readonly [a in b]: c }"),
            ("MappedTypeNode#4", "type T = { +readonly [a in b]: c }"),
            ("MappedTypeNode#5", "type T = { -readonly [a in b]: c }"),
            ("MappedTypeNode#6", "type T = { [a in b]?: c }"),
            ("MappedTypeNode#7", "type T = { [a in b]+?: c }"),
            ("MappedTypeNode#8", "type T = { [a in b]-?: c }"),
            ("MappedTypeNode#9", "type T = { [a in b]: c; d }"),
            ("LiteralTypeNode#1", "type T = null"),
            ("LiteralTypeNode#2", "type T = true"),
            ("LiteralTypeNode#3", "type T = false"),
            ("LiteralTypeNode#4", "type T = \"\""),
            ("LiteralTypeNode#5", "type T = ''"),
            ("LiteralTypeNode#6", "type T = ``"),
            ("LiteralTypeNode#7", "type T = 0"),
            ("LiteralTypeNode#8", "type T = 0n"),
            ("LiteralTypeNode#9", "type T = -0"),
            ("LiteralTypeNode#10", "type T = -0n"),
            ("TemplateTypeNode#1", "type T = `a${b}c`"),
            ("TemplateTypeNode#2", "type T = `a${b}c${d}e`"),
            ("ImportTypeNode#1", "type T = import(a)"),
            ("ImportTypeNode#2", "type T = import(a).b"),
            ("ImportTypeNode#3", "type T = import(a).b<U>"),
            ("ImportTypeNode#4", "type T = typeof import(a)"),
            ("ImportTypeNode#5", "type T = typeof import(a).b"),
            ("ImportTypeNode#6a", "type T = import(a, { with: { } })"),
            (
                "ImportTypeNode#6b",
                "type T = import(a, { with: { b: \"c\" } })",
            ),
            (
                "ImportTypeNode#7",
                "type T = import(a, { with: { \"b\": \"c\" } })",
            ),
            ("PropertySignature#1", "interface I {a}"),
            ("PropertySignature#2", "interface I {readonly a}"),
            ("PropertySignature#3", "interface I {\"a\"}"),
            ("PropertySignature#4", "interface I {'a'}"),
            ("PropertySignature#5", "interface I {0}"),
            ("PropertySignature#6", "interface I {0n}"),
            ("PropertySignature#7", "interface I {[a]}"),
            ("PropertySignature#8", "interface I {a?}"),
            ("PropertySignature#9", "interface I {a: b}"),
            ("MethodSignature#1", "interface I {a()}"),
            ("MethodSignature#2", "interface I {\"a\"()}"),
            ("MethodSignature#3", "interface I {'a'()}"),
            ("MethodSignature#4", "interface I {0()}"),
            ("MethodSignature#5", "interface I {0n()}"),
            ("MethodSignature#6", "interface I {[a]()}"),
            ("MethodSignature#7", "interface I {a?()}"),
            ("MethodSignature#8", "interface I {a<T>()}"),
            ("MethodSignature#9", "interface I {a(): b}"),
            ("MethodSignature#10", "interface I {a(b): c}"),
            ("CallSignature#1", "interface I {()}"),
            ("CallSignature#2", "interface I {():a}"),
            ("CallSignature#3", "interface I {(p)}"),
            ("CallSignature#4", "interface I {<T>()}"),
            ("ConstructSignature#1", "interface I {new ()}"),
            ("ConstructSignature#2", "interface I {new ():a}"),
            ("ConstructSignature#3", "interface I {new (p)}"),
            ("ConstructSignature#4", "interface I {new <T>()}"),
            ("IndexSignatureDeclaration#1", "interface I {[a]}"),
            ("IndexSignatureDeclaration#2", "interface I {[a: b]}"),
            ("IndexSignatureDeclaration#3", "interface I {[a: b]: c}"),
            ("PropertyDeclaration#1", "class C {a}"),
            ("PropertyDeclaration#2", "class C {readonly a}"),
            ("PropertyDeclaration#3", "class C {static a}"),
            ("PropertyDeclaration#4", "class C {accessor a}"),
            ("PropertyDeclaration#5", "class C {\"a\"}"),
            ("PropertyDeclaration#6", "class C {'a'}"),
            ("PropertyDeclaration#7", "class C {0}"),
            ("PropertyDeclaration#8", "class C {0n}"),
            ("PropertyDeclaration#9", "class C {[a]}"),
            ("PropertyDeclaration#10", "class C {#a}"),
            ("PropertyDeclaration#11", "class C {a?}"),
            ("PropertyDeclaration#12", "class C {a!}"),
            ("PropertyDeclaration#13", "class C {a: b}"),
            ("PropertyDeclaration#14", "class C {a = b}"),
            ("PropertyDeclaration#15", "class C {@a b}"),
            ("MethodDeclaration#1", "class C {a()}"),
            ("MethodDeclaration#2", "class C {\"a\"()}"),
            ("MethodDeclaration#3", "class C {'a'()}"),
            ("MethodDeclaration#4", "class C {0()}"),
            ("MethodDeclaration#5", "class C {0n()}"),
            ("MethodDeclaration#6", "class C {[a]()}"),
            ("MethodDeclaration#7", "class C {#a()}"),
            ("MethodDeclaration#8", "class C {a?()}"),
            ("MethodDeclaration#9", "class C {a<T>()}"),
            ("MethodDeclaration#10", "class C {a(): b}"),
            ("MethodDeclaration#11", "class C {a(b): c}"),
            ("MethodDeclaration#12", "class C {a() {} }"),
            ("MethodDeclaration#13", "class C {@a b() {} }"),
            ("MethodDeclaration#14", "class C {static a() {} }"),
            ("MethodDeclaration#15", "class C {async a() {} }"),
            ("GetAccessorDeclaration#1", "class C {get a()}"),
            ("GetAccessorDeclaration#2", "class C {get \"a\"()}"),
            ("GetAccessorDeclaration#3", "class C {get 'a'()}"),
            ("GetAccessorDeclaration#4", "class C {get 0()}"),
            ("GetAccessorDeclaration#5", "class C {get 0n()}"),
            ("GetAccessorDeclaration#6", "class C {get [a]()}"),
            ("GetAccessorDeclaration#7", "class C {get #a()}"),
            ("GetAccessorDeclaration#8", "class C {get a(): b}"),
            ("GetAccessorDeclaration#9", "class C {get a(b): c}"),
            ("GetAccessorDeclaration#10", "class C {get a() {} }"),
            ("GetAccessorDeclaration#11", "class C {@a get b() {} }"),
            ("GetAccessorDeclaration#12", "class C {static get a() {} }"),
            ("SetAccessorDeclaration#1", "class C {set a()}"),
            ("SetAccessorDeclaration#2", "class C {set \"a\"()}"),
            ("SetAccessorDeclaration#3", "class C {set 'a'()}"),
            ("SetAccessorDeclaration#4", "class C {set 0()}"),
            ("SetAccessorDeclaration#5", "class C {set 0n()}"),
            ("SetAccessorDeclaration#6", "class C {set [a]()}"),
            ("SetAccessorDeclaration#7", "class C {set #a()}"),
            ("SetAccessorDeclaration#8", "class C {set a(): b}"),
            ("SetAccessorDeclaration#9", "class C {set a(b): c}"),
            ("SetAccessorDeclaration#10", "class C {set a() {} }"),
            ("SetAccessorDeclaration#11", "class C {@a set b() {} }"),
            ("SetAccessorDeclaration#12", "class C {static set a() {} }"),
            ("ConstructorDeclaration#1", "class C {constructor()}"),
            ("ConstructorDeclaration#2", "class C {constructor(): b}"),
            ("ConstructorDeclaration#3", "class C {constructor(b): c}"),
            ("ConstructorDeclaration#4", "class C {constructor() {} }"),
            ("ConstructorDeclaration#5", "class C {@a constructor() {} }"),
            (
                "ConstructorDeclaration#6",
                "class C {private constructor() {} }",
            ),
            ("ClassStaticBlockDeclaration", "class C {static { }}"),
            ("SemicolonClassElement#1", "class C {;}"),
            ("ParameterDeclaration#1", "function f(a)"),
            ("ParameterDeclaration#2", "function f(a: b)"),
            ("ParameterDeclaration#3", "function f(a = b)"),
            ("ParameterDeclaration#4", "function f(a?)"),
            ("ParameterDeclaration#5", "function f(...a)"),
            ("ParameterDeclaration#6", "function f(this)"),
            ("ParameterDeclaration#7", "function f(a,)"),
            ("ObjectBindingPattern#1", "function f({})"),
            ("ObjectBindingPattern#2", "function f({a})"),
            ("ObjectBindingPattern#3", "function f({a = b})"),
            ("ObjectBindingPattern#4", "function f({a: b})"),
            ("ObjectBindingPattern#5", "function f({a: b = c})"),
            ("ObjectBindingPattern#6", "function f({\"a\": b})"),
            ("ObjectBindingPattern#7", "function f({'a': b})"),
            ("ObjectBindingPattern#8", "function f({0: b})"),
            ("ObjectBindingPattern#9", "function f({[a]: b})"),
            ("ObjectBindingPattern#10", "function f({...a})"),
            ("ObjectBindingPattern#11", "function f({a: {}})"),
            ("ObjectBindingPattern#12", "function f({a: []})"),
            ("ArrayBindingPattern#1", "function f([])"),
            ("ArrayBindingPattern#2", "function f([,])"),
            ("ArrayBindingPattern#3", "function f([a])"),
            ("ArrayBindingPattern#4", "function f([a, b])"),
            ("ArrayBindingPattern#5", "function f([a, , b])"),
            ("ArrayBindingPattern#6", "function f([a = b])"),
            ("ArrayBindingPattern#7", "function f([...a])"),
            ("ArrayBindingPattern#8", "function f([{}])"),
            ("ArrayBindingPattern#9", "function f([[]])"),
            ("TypeParameterDeclaration#1", "function f<T>();"),
            ("TypeParameterDeclaration#2", "function f<in T>();"),
            ("TypeParameterDeclaration#3", "function f<T extends U>();"),
            ("TypeParameterDeclaration#4", "function f<T = U>();"),
            (
                "TypeParameterDeclaration#5",
                "function f<T extends U = V>();",
            ),
            ("TypeParameterDeclaration#6", "function f<T, U>();"),
            ("TypeParameterDeclaration#7", "function f<T,>();"),
            ("JsxElement1", "<a></a>"),
            ("JsxElement2", "<this></this>"),
            ("JsxElement3", "<a:b></a:b>"),
            ("JsxElement4", "<a.b></a.b>"),
            ("JsxElement5", "<a<b>></a>"),
            ("JsxElement6", "<a b></a>"),
            ("JsxElement7", "<a>b</a>"),
            ("JsxElement8", "<a>{b}</a>"),
            ("JsxElement9", "<a><b></b></a>"),
            ("JsxElement10", "<a><b /></a>"),
            ("JsxElement11", "<a><></></a>"),
            ("JsxSelfClosingElement1", "<a />"),
            ("JsxSelfClosingElement2", "<this />"),
            ("JsxSelfClosingElement3", "<a:b />"),
            ("JsxSelfClosingElement4", "<a.b />"),
            ("JsxSelfClosingElement5", "<a<b> />"),
            ("JsxSelfClosingElement6", "<a b/>"),
            ("JsxFragment1", "<></>"),
            ("JsxFragment2", "<>b</>"),
            ("JsxFragment3", "<>{b}</>"),
            ("JsxFragment4", "<><b></b></>"),
            ("JsxFragment5", "<><b /></>"),
            ("JsxFragment6", "<><></></>"),
            ("JsxAttribute1", "<a b/>"),
            ("JsxAttribute2", "<a b:c/>"),
            ("JsxAttribute3", "<a b=\"c\"/>"),
            ("JsxAttribute4", "<a b='c'/>"),
            ("JsxAttribute5", "<a b={c}/>"),
            ("JsxAttribute6", "<a b=<c></c>/>"),
            ("JsxAttribute7", "<a b=<c />/>"),
            ("JsxAttribute8", "<a b=<></>/>"),
            ("JsxSpreadAttribute", "<a {...b}/>"),
        ];

        // For each snippet, parse it, produce a structural clone, and verify
        // the clone shares the root allocation and is structurally identical
        // to the original (equal kind, source range, and child tree, walked in
        // lockstep via `for_each_child`).
        for &(title, input) in cases {
            let file = crate::parser::Parser::parse_source_file_text("/f.ts", input.to_string());
            let original = Arc::clone(&file.node);
            let clone = deep_clone_node(&original);

            // The simplified clone shares the root allocation.
            assert!(
                Arc::ptr_eq(&original, &clone),
                "{title}: clone should share the root allocation"
            );
            // ... and is structurally identical to the original.
            assert_same_structure(&original, &clone);
        }
    }
}
