//! Core AST node types.
//!
//! Ported from `internal/ast/ast.go`. The Go implementation uses a
//! `nodeData` interface with hundreds of implementations and type
//! switches. In Rust we use an enum (`NodeData`) with one variant per
//! node kind, and pattern matching for accessors.
//!
//! The `NodeData` enum and per-node data structs are generated from
//! `_scripts/ast.json` by `_scripts/generate-rust-ast.ts`. See
//! `node_data_generated.rs`.

use super::node_data_generated::NodeData;
use super::node_flags::{ModifierFlags, NodeFlags};
use super::SyntaxKind;
use crate::core::text::TextRange;
use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::Arc;

/// A unique ID assigned to each node for debugging and caching.
static NEXT_NODE_ID: AtomicU64 = AtomicU64::new(1);

/// The core AST node.
///
/// Mirrors `ast.Node` in Go. A node carries its kind, flags, source
/// location, parent pointer, and kind-specific data.
#[derive(Debug)]
pub struct Node {
    pub kind: SyntaxKind,
    pub flags: NodeFlags,
    pub loc: TextRange,
    id: AtomicU64,
    pub parent: Option<Arc<Node>>,
    pub data: NodeData,
}

impl Node {
    pub fn new(kind: SyntaxKind, data: NodeData) -> Self {
        Self {
            kind,
            flags: NodeFlags::empty(),
            loc: TextRange::undefined(),
            id: AtomicU64::new(0),
            parent: None,
            data,
        }
    }

    /// Create a node with a specific kind, data, and source location.
    pub fn with_loc(kind: SyntaxKind, data: NodeData, loc: TextRange) -> Self {
        Self {
            kind,
            flags: NodeFlags::empty(),
            loc,
            id: AtomicU64::new(0),
            parent: None,
            data,
        }
    }

    #[inline]
    pub fn pos(&self) -> usize {
        self.loc.pos()
    }

    #[inline]
    pub fn end(&self) -> usize {
        self.loc.end()
    }

    /// A unique numeric ID for this node (lazily assigned).
    pub fn id(&self) -> u64 {
        let mut id = self.id.load(Ordering::Relaxed);
        if id == 0 {
            id = NEXT_NODE_ID.fetch_add(1, Ordering::Relaxed);
            self.id.store(id, Ordering::Relaxed);
        }
        id
    }

    /// The text content of literal/identifier nodes.
    ///
    /// Mirrors `Node.Text()` in Go.
    pub fn text(&self) -> &str {
        crate::ast::node_data_generated::node_text(self)
    }

    /// The primary expression child of this node, if any.
    ///
    /// Mirrors `Node.Expression()` in Go.
    pub fn expression(&self) -> Option<&Arc<Node>> {
        crate::ast::node_data_generated::node_expression(self)
    }

    /// The type child of a type node, if any.
    ///
    /// Mirrors `Node.Type()` in Go.
    pub fn type_node(&self) -> Option<&Arc<Node>> {
        crate::ast::node_data_generated::node_type(self)
    }

    /// The name of a declaration, if any.
    ///
    /// Mirrors `Node.Name()` in Go.
    pub fn name(&self) -> Option<&Arc<Node>> {
        crate::ast::node_data_generated::node_name(self)
    }
}

/// A list of nodes, preserving source location.
///
/// Mirrors `ast.NodeList` in Go.
#[derive(Debug, Default)]
pub struct NodeList {
    pub loc: TextRange,
    pub nodes: Vec<Arc<Node>>,
}

impl NodeList {
    pub fn new(nodes: Vec<Arc<Node>>) -> Self {
        Self {
            loc: TextRange::undefined(),
            nodes,
        }
    }

    #[inline]
    pub fn pos(&self) -> usize {
        self.loc.pos()
    }

    #[inline]
    pub fn end(&self) -> usize {
        self.loc.end()
    }

    pub fn has_trailing_comma(&self) -> bool {
        if self.nodes.is_empty() {
            return false;
        }
        let last = self.nodes.last().unwrap();
        last.end() < self.end()
    }

    pub fn len(&self) -> usize {
        self.nodes.len()
    }

    pub fn is_empty(&self) -> bool {
        self.nodes.is_empty()
    }

    pub fn iter(&self) -> std::slice::Iter<'_, Arc<Node>> {
        self.nodes.iter()
    }
}

/// A list of modifier tokens, with cached flags.
///
/// Mirrors `ast.ModifierList` in Go.
#[derive(Debug, Default)]
pub struct ModifierList {
    pub list: NodeList,
    pub modifier_flags: ModifierFlags,
}

impl ModifierList {
    pub fn new(nodes: Vec<Arc<Node>>, flags: ModifierFlags) -> Self {
        Self {
            list: NodeList::new(nodes),
            modifier_flags: flags,
        }
    }

    pub fn flags(&self) -> ModifierFlags {
        self.modifier_flags
    }
}

impl std::ops::Deref for ModifierList {
    type Target = NodeList;

    fn deref(&self) -> &Self::Target {
        &self.list
    }
}

// ────────────────────────────────────────────────────────────────────────────
// Node data variants — now generated by _scripts/generate-rust-ast.ts
// See node_data_generated.rs for the NodeData enum and all *Data structs.
// ────────────────────────────────────────────────────────────────────────────

/// A source file (the root of an AST).
///
/// Mirrors `ast.SourceFile` in Go.
#[derive(Debug)]
pub struct SourceFile {
    pub node: Arc<Node>,
    pub file_name: String,
    pub text: String,
    pub line_map: LineMap,
    pub language_variant: LanguageVariant,
    pub script_kind: ScriptKind,
}

impl SourceFile {
    /// A unique numeric ID for this source file (delegates to its node).
    pub fn id(&self) -> u64 {
        self.node.id()
    }
}

/// A mapping from line number to byte offset in the source text.
#[derive(Debug, Default)]
pub struct LineMap {
    pub line_starts: Vec<u32>,
}

impl LineMap {
    pub fn from_text(text: &str) -> Self {
        let mut line_starts = vec![0u32];
        for (i, c) in text.char_indices() {
            if c == '\n' {
                line_starts.push((i + 1) as u32);
            }
        }
        Self { line_starts }
    }

    /// Get the line number (0-based) for a byte offset.
    pub fn line_at(&self, offset: usize) -> usize {
        match self.line_starts.binary_search(&(offset as u32)) {
            Ok(i) => i,
            Err(i) => i.saturating_sub(1),
        }
    }

    /// Get the column number (0-based) for a byte offset.
    pub fn column_at(&self, offset: usize) -> usize {
        let line = self.line_at(offset);
        let line_start = self.line_starts[line] as usize;
        offset - line_start
    }
}

/// Language variant (Standard or JSX).
///
/// Mirrors `core.LanguageVariant` in Go.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum LanguageVariant {
    #[default]
    Standard,
    Jsx,
}

/// Script kind (TS, JS, JSON, etc.).
///
/// Mirrors `core.ScriptKind` in Go.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum ScriptKind {
    #[default]
    Ts,
    Js,
    Json,
    External,
    Deferred,
}

#[cfg(test)]
mod tests {
    use super::*;
    use super::super::node_data_generated::IdentifierData;

    #[test]
    fn identifier_node() {
        let node = Node::new(
            SyntaxKind::Identifier,
            NodeData::Identifier(IdentifierData {
                text: "foo".to_string(),
            }),
        );
        assert_eq!(node.kind, SyntaxKind::Identifier);
        assert_eq!(node.text(), "foo");
    }

    #[test]
    fn node_ids_are_unique() {
        let n1 = Node::new(SyntaxKind::Unknown, NodeData::Token);
        let n2 = Node::new(SyntaxKind::Unknown, NodeData::Token);
        assert_ne!(n1.id(), n2.id());
    }

    #[test]
    fn line_map_basic() {
        let lm = LineMap::from_text("abc\ndef\nghi");
        assert_eq!(lm.line_starts, vec![0, 4, 8]);
        assert_eq!(lm.line_at(0), 0);
        assert_eq!(lm.line_at(3), 0);
        assert_eq!(lm.line_at(4), 1);
        assert_eq!(lm.line_at(7), 1);
        assert_eq!(lm.line_at(8), 2);
    }
}
