// Reads the Go-generated `diagnostics_generated.go` and emits the Rust
// `messages_generated.rs`. The output is byte-for-byte stable so it can be
// checked into source control and regenerated without producing diffs.

import * as fs from "node:fs";
import * as path from "node:path";

interface ParsedMessage {
    varName: string;
    constName: string;
    code: string;
    category: string;
    key: string;
    text: string;
    reportsUnnecessary: boolean;
    elidedInCompatibilityPyramid: boolean;
    reportsDeprecated: boolean;
}

const CATEGORY_MAP: Record<string, string> = {
    CategoryError: "Category::Error",
    CategoryWarning: "Category::Warning",
    CategorySuggestion: "Category::Suggestion",
    CategoryMessage: "Category::Message",
};

const scriptDir = import.meta.dirname;
const repoRoot = path.resolve(scriptDir, "..");
const goInputPath = path.resolve(
    repoRoot,
    "..",
    "typescript-go",
    "internal",
    "diagnostics",
    "diagnostics_generated.go",
);
const rustOutputPath = path.join(repoRoot, "src", "diagnostics", "messages_generated.rs");

// Matches a line like:
//   var Unterminated_string_literal = &Message{code: 1002, category: CategoryError, key: "Unterminated_string_literal_1002", text: "Unterminated string literal."}
// The optional trailing group captures flags such as `, reportsDeprecated: true`.
const VAR_RE =
    /^var (\w+) = &Message\{code: (\d+), category: (\w+), key: "(.*)", text: "(.*)"(.*?)\}$/;

function parseGoFile(filePath: string): ParsedMessage[] {
    const content = fs.readFileSync(filePath, "utf8").replace(/\r\n/g, "\n");
    const messages: ParsedMessage[] = [];
    for (const line of content.split("\n")) {
        const m = VAR_RE.exec(line);
        if (!m) continue;
        const [, varName, code, category, key, text, rest] = m;
        messages.push({
            varName,
            constName: varName.toUpperCase(),
            code,
            category: CATEGORY_MAP[category] ?? category,
            key,
            text,
            reportsUnnecessary: rest.includes("reportsUnnecessary: true"),
            elidedInCompatibilityPyramid: rest.includes("elidedInCompatibilityPyramid: true"),
            reportsDeprecated: rest.includes("reportsDeprecated: true"),
        });
    }
    return messages;
}

function formatMessage(m: ParsedMessage): string {
    const name = m.constName;
    const n = name.length;

    // The declaration `pub static ${name}: Message = Message {` is 32 + n chars.
    // The existing file wraps it in three bands (with a fallback to inline for
    // very long names), so we reproduce that exactly:
    //   n <= 67 (decl <= 99):  inline
    //   68..78 (100..110):     split before `Message {`, indent fields 8 spaces
    //   79..85 (111..117):     split after `:`, indent fields 4 spaces
    //   n >= 86 (decl >= 118): inline (fallback)
    let form: 1 | 2 | 3;
    if (n <= 67) {
        form = 1;
    } else if (n <= 78) {
        form = 2;
    } else if (n <= 85) {
        form = 3;
    } else {
        form = 1;
    }

    const fields = [
        `    code: ${m.code},`,
        `    category: ${m.category},`,
        `    key: "${m.key}",`,
        `    text: "${m.text}",`,
        `    reports_unnecessary: ${m.reportsUnnecessary},`,
        `    elided_in_compatibility_pyramid: ${m.elidedInCompatibilityPyramid},`,
        `    reports_deprecated: ${m.reportsDeprecated},`,
    ];

    if (form === 1) {
        return `pub static ${name}: Message = Message {\n${fields.join("\n")}\n};`;
    }
    if (form === 2) {
        const inner = fields.map((f) => `    ${f}`).join("\n");
        return `pub static ${name}: Message =\n    Message {\n${inner}\n    };`;
    }
    return `pub static ${name}:\n    Message = Message {\n${fields.join("\n")}\n};`;
}

function generate(messages: ParsedMessage[]): string {
    const parts: string[] = [];
    parts.push("// Code generated by _scripts/generate-rust-diagnostics.ts. DO NOT EDIT.");
    parts.push("");
    parts.push("//! Generated diagnostic message constants.");
    parts.push("//!");
    parts.push("//! This file is automatically generated from the Go-generated");
    parts.push("//! `diagnostics_generated.go`. Do not edit manually.");
    parts.push("");
    parts.push("use super::{Category, Key, Message};");
    parts.push("");
    for (let i = 0; i < messages.length; i++) {
        if (i > 0) parts.push("");
        parts.push(formatMessage(messages[i]));
    }
    parts.push("");
    parts.push("/// Look up a message by its key.");
    parts.push("pub fn key_to_message(key: Key) -> Option<&'static Message> {");
    parts.push("    match key {");
    for (const m of messages) {
        parts.push(`        "${m.key}" => Some(&${m.constName}),`);
    }
    parts.push("        _ => None,");
    parts.push("    }");
    parts.push("}");
    return parts.join("\n") + "\n";
}

function main(): void {
    const messages = parseGoFile(goInputPath);
    if (messages.length === 0) {
        console.error(`No messages parsed from ${goInputPath}`);
        process.exit(1);
    }
    const output = generate(messages);
    fs.writeFileSync(rustOutputPath, output);
    console.log(`Generated ${messages.length} messages to ${rustOutputPath}`);
}

main();
