#![allow(unused_imports)]
use crate::checker::checker_checker::*;
pub struct Checker {
    pub id: u32,
    pub program: Arc<dyn Program>,
    pub compiler_options: Arc<CompilerOptions>,
    pub files: Vec<Arc<SourceFile>>,
    pub file_index_map: HashMap<u64, usize>,
    pub type_count: u32,
    pub symbol_count: u32,
    pub signature_count: u32,
    pub total_instantiation_count: u32,
    pub instantiation_count: u32,
    pub instantiation_depth: u32,
    /// type_of_imported_symbol 访问中环守卫（Go symbolLinks 解析中缓存）
    pub imported_type_resolution: Vec<u64>,
    pub alias_type_resolution_stack: Vec<u64>,
    pub language_version: ScriptTarget,
    pub module_kind: ModuleKind,
    pub module_resolution_kind: ModuleResolutionKind,
    pub legacy_decorators: bool,
    pub emit_standard_class_fields: bool,
    pub strict_null_checks: bool,
    pub allow_unreachable_code: tsox_core::core::tristate::Tristate,
    pub allow_unused_labels: tsox_core::core::tristate::Tristate,
    pub within_unreachable_code: bool,
    pub interface_build_depth: usize,
    pub reported_unreachable_nodes: std::collections::HashSet<usize>,
    pub strict_function_types: bool,
    pub strict_bind_call_apply: bool,
    pub strict_property_initialization: bool,
    pub strict_builtin_iterator_return: bool,
    pub no_implicit_any: bool,
    pub no_implicit_this: bool,
    pub use_unknown_in_catch_variables: bool,
    pub exact_optional_property_types: bool,
    pub can_collect_symbol_alias_accessibility_data: bool,
    pub globals: SymbolTable,
    pub undefined_symbol: Option<Arc<Symbol>>,
    pub arguments_symbol: Option<Arc<Symbol>>,
    pub require_symbol: Option<Arc<Symbol>>,
    pub unknown_symbol: Option<Arc<Symbol>>,
    pub global_this_symbol: Option<Arc<Symbol>>,
    pub string_literal_types: HashMap<String, Arc<Type>>,
    pub number_literal_types: HashMap<tsox_core::jsnum::Number, Arc<Type>>,
    pub bigint_literal_types: HashMap<String, Arc<Type>>,
    pub unique_es_symbol_types: HashMap<u64, Arc<Type>>,
    pub nan_type: Option<Arc<Type>>,
    pub indexed_access_types: HashMap<CacheHashKey, Arc<Type>>,
    pub template_literal_types: HashMap<CacheHashKey, Arc<Type>>,
    pub string_mapping_types: HashMap<u64, Arc<Type>>,
    pub cached_types: HashMap<CachedTypeKey, Arc<Type>>,
    pub union_types: HashMap<CacheHashKey, Arc<Type>>,
    pub intersection_types: HashMap<CacheHashKey, Arc<Type>>,
    pub tuple_types: HashMap<CacheHashKey, Arc<Type>>,
    pub error_types: HashMap<CacheHashKey, Arc<Type>>,
    pub global_interface_members: HashMap<String, Vec<String>>,
    pub boxed_global_types: HashMap<String, Arc<Type>>,
    pub diagnostics: DiagnosticsCollection,
    pub suggestion_diagnostics: DiagnosticsCollection,
    pub node_links: LinkStore<Node, NodeLinks>,
    pub signature_links: LinkStore<Node, SignatureLinks>,
    pub symbol_node_links: LinkStore<Node, SymbolNodeLinks>,
    pub type_node_links: LinkStore<Node, TypeNodeLinks>,
    pub enum_member_links: LinkStore<Node, EnumMemberLinks>,
    pub assertion_links: LinkStore<Node, AssertionLinks>,
    pub array_literal_links: LinkStore<Node, ArrayLiteralLinks>,
    pub switch_statement_links: LinkStore<Node, SwitchStatementLinks>,
    pub jsx_element_links: LinkStore<Node, JsxElementLinks>,
    pub symbol_reference_links: LinkStore<Symbol, SymbolReferenceLinks>,
    pub value_symbol_links: LinkStore<Symbol, ValueSymbolLinks>,
    pub mapped_symbol_links: LinkStore<Symbol, MappedSymbolLinks>,
    pub deferred_symbol_links: LinkStore<Symbol, DeferredSymbolLinks>,
    pub alias_symbol_links: LinkStore<Symbol, AliasSymbolLinks>,
    pub module_symbol_links: LinkStore<Symbol, ModuleSymbolLinks>,
    pub late_bound_links: LinkStore<Symbol, LateBoundLinks>,
    pub export_type_links: LinkStore<Symbol, ExportTypeLinks>,
    pub members_and_exports_links: LinkStore<Symbol, MembersAndExportsLinks>,
    pub type_alias_links: LinkStore<Symbol, TypeAliasLinks>,
    pub declared_type_links: LinkStore<Symbol, DeclaredTypeLinks>,
    pub class_instance_type_cache: HashMap<u64, Arc<Type>>,
    pub type_resolution_stack: Vec<TypeResolutionEntry>,
    pub type_argument_stack: Vec<HashMap<*const tsox_frontend::ast::Symbol, Arc<Type>>>,
    pub type_argument_name_frames: Vec<Vec<(Arc<Symbol>, Arc<Type>)>>,
    pub type_node_subst_cache: HashMap<(usize, u64), Arc<Type>>,
    pub type_node_resolving: HashSet<(usize, u64)>,
    pub type_resolution_depth: u32,
    pub speculation_depth: u32,
    pub heritage_degraded_events: u64,
    pub type_node_query_epochs: Vec<u64>,
    pub heritage_retry_counts: HashMap<usize, u32>,
    pub type_node_subst_cache_limit: usize,
    pub type_parameter_resolving: HashSet<usize>,
    pub ts2313_reported: HashSet<usize>,
    pub ts2354_checked_files: HashSet<usize>,
    pub requested_external_emit_helpers: HashMap<usize, u32>,
    pub degraded_type_ptrs: std::collections::HashSet<u32>,
    pub jsx_implicit_namespace: HashMap<usize, Option<Arc<Symbol>>>,
    pub pending_jsx_2875: Option<(tsox_core::core::text::TextRange, String)>,
    pub relater_error_chain: Vec<RelaterChainEntry>,
    pub relater_chain_active: bool,
    pub relater_depth: u32,
    pub deferred_constraint_depth: u32,
    pub relation_count: u32,
    pub relater_overflow: bool,
    pub relater_intersection_target_depth: u32,
    pub subst_object_in_progress: std::collections::HashMap<u32, Arc<crate::checker::types::Type>>,
    pub in_return_substitution: bool,
    pub relater_source_stack: Vec<Arc<Type>>,
    pub relater_target_stack: Vec<Arc<Type>>,
    pub relation_cache: HashMap<crate::checker::relater::RelationCacheKey, bool>,
    pub probe_cache_permissive: HashMap<u32, Arc<Type>>,
    pub probe_cache_restrictive: HashMap<u32, Arc<Type>>,
    pub enum_relation: HashMap<EnumRelationKey, crate::checker::relater::RelationComparisonResult>,
    pub relation_in_progress: std::collections::HashSet<crate::checker::relater::RelationCacheKey>,
    pub interface_extends_reported: std::collections::HashSet<(
        *const tsox_frontend::ast::Symbol,
        *const tsox_frontend::ast::Node,
    )>,
    pub interface_simultaneous_reported: std::collections::HashSet<*const tsox_frontend::ast::Symbol>,
    pub indexed_access_2538_reported: std::collections::HashSet<*const tsox_frontend::ast::Node>,
    pub arith_operand_error_nodes: std::collections::HashSet<*const tsox_frontend::ast::Node>,
    pub computed_property_name_checked: std::collections::HashSet<*const tsox_frontend::ast::Node>,
    pub symbol_reference_kinds: dashmap::DashMap<u64, SymbolFlags>,
    pub spread_links: LinkStore<Symbol, SpreadLinks>,
    pub variance_links: LinkStore<Symbol, VarianceLinks>,
    pub reverse_mapped_symbol_links: LinkStore<Symbol, ReverseMappedSymbolLinks>,
    pub reverse_mapped_cache: HashMap<(u32, u32, u32), Option<Arc<Type>>>,
    pub template_resolving_ids: std::collections::HashSet<u32>,
    pub template_resolution_letway: bool,
    pub deferred_indexed_access_cache: HashMap<(u32, u32), Arc<Type>>,
    pub index_type_cache: HashMap<u32, Arc<Type>>,
    pub interface_shell_reify_cache: HashMap<usize, Arc<Type>>,
    pub reverse_mapped_print_stack: Vec<Arc<Symbol>>,
    pub alias_args_resolution_stack: Vec<(usize, Vec<u32>)>,
    pub alias_instantiation_cache: HashMap<(usize, Vec<u32>), Arc<Type>>,
    pub current_alias_frame: Option<(usize, Vec<u32>)>,
    pub reverse_mapped_depth: Vec<u32>,
    pub reverse_mapped_target_depth: Vec<u32>,
    pub marked_assignment_symbol_links: LinkStore<Symbol, MarkedAssignmentSymbolLinks>,
    pub symbol_container_links: LinkStore<Symbol, ContainingSymbolLinks>,
    pub symbol_table_alias_cache: HashMap<u64, Vec<Arc<Symbol>>>,
    pub class_expression_name_tables: HashMap<u64, SymbolTable>,
    pub source_file_links: LinkStore<SourceFile, SourceFileLinks>,
    pub declaration_links: LinkStore<Node, DeclarationLinks>,
    pub declaration_file_links: LinkStore<SourceFile, DeclarationFileLinks>,
    pub(crate) last_combined_modifier_flags_node: Option<Arc<Node>>,
    pub(crate) last_combined_modifier_flags_result: ModifierFlags,
    pub any_type: OnceLock<Arc<Type>>,
    pub unknown_type: OnceLock<Arc<Type>>,
    pub undefined_type: OnceLock<Arc<Type>>,
    pub null_type: OnceLock<Arc<Type>>,
    pub string_type: OnceLock<Arc<Type>>,
    pub number_type: OnceLock<Arc<Type>>,
    pub bigint_type: OnceLock<Arc<Type>>,
    pub boolean_type: OnceLock<Arc<Type>>,
    pub es_symbol_type: OnceLock<Arc<Type>>,
    pub void_type: OnceLock<Arc<Type>>,
    pub never_type: OnceLock<Arc<Type>>,
    pub silent_never_type: OnceLock<Arc<Type>>,
    pub non_primitive_type: OnceLock<Arc<Type>>,
    pub true_type: OnceLock<Arc<Type>>,
    pub false_type: OnceLock<Arc<Type>>,
    pub error_type: OnceLock<Arc<Type>>,
    pub unresolved_type: OnceLock<Arc<Type>>,
    pub auto_type: OnceLock<Arc<Type>>,
    pub empty_object_type: OnceLock<Arc<Type>>,
    pub empty_generic_type: OnceLock<Arc<Type>>,
    pub any_function_type: OnceLock<Arc<Type>>,
    pub no_constraint_type: OnceLock<Arc<Type>>,
    pub circular_constraint_type: OnceLock<Arc<Type>>,
    pub any_array_type: OnceLock<Arc<Type>>,
    pub auto_array_type: OnceLock<Arc<Type>>,
    pub any_readonly_array_type: OnceLock<Arc<Type>>,
    pub global_object_type: OnceLock<Arc<Type>>,
    pub global_function_type: OnceLock<Arc<Type>>,
    pub global_array_type: OnceLock<Arc<Type>>,
    pub global_readonly_array_type: OnceLock<Arc<Type>>,
    pub global_string_type: OnceLock<Arc<Type>>,
    pub global_number_type: OnceLock<Arc<Type>>,
    pub global_boolean_type: OnceLock<Arc<Type>>,
    pub global_reg_exp_type: OnceLock<Arc<Type>>,
    pub global_this_type: OnceLock<Arc<Type>>,
    pub global_promise_type: OnceLock<Arc<Type>>,
    pub array_type_cache: std::collections::HashMap<(usize, usize), Arc<Type>>,
    pub interface_instantiation_cache:
        std::collections::HashMap<Vec<usize>, (Vec<Arc<Type>>, Arc<Type>)>,
    pub merged_ns_instance_type_cache: std::collections::HashMap<u64, Arc<Type>>,
    pub pending_interface_shells: std::collections::HashMap<usize, Arc<Type>>,
    pub attached_type_args_cache:
        std::collections::HashMap<Vec<usize>, (Arc<Type>, Vec<Arc<Type>>, Arc<Type>)>,
    pub filling_class_members: std::collections::HashSet<u64>,
    pub class_build_in_progress: std::collections::HashSet<u64>,
    pub pending_base_merges: Vec<(u64, Arc<Type>)>,
    pub typequery_instantiation_cache:
        std::collections::HashMap<Vec<usize>, (Vec<Arc<Type>>, Arc<Type>)>,
    pub array_type_parameter_symbols: Option<Vec<Arc<tsox_frontend::ast::Symbol>>>,
    pub array_member_type_cache: std::collections::HashMap<(usize, usize), Arc<Type>>,
    pub array_type_intern_cache: std::collections::HashMap<(u32, bool), Arc<Type>>,
    pub instantiated_member_type_cache:
        std::collections::HashMap<(usize, usize), (Arc<Type>, Arc<Type>)>,
    pub instantiated_member_type_cache_limit: usize,
    pub instantiated_member_owner: std::collections::HashMap<usize, u64>,
    pub any_signature: OnceLock<Arc<Signature>>,
    pub unknown_signature: OnceLock<Arc<Signature>>,
    pub resolving_signature: OnceLock<Arc<Signature>>,
    pub current_node: Option<Arc<Node>>,
    pub inline_level: i32,
    pub serialization_level: i32,
    pub type_print_stack: Vec<usize>,
    pub current_file: Option<Arc<SourceFile>>,
    pub current_file_id: u64,
    pub display_enclosing_file: Option<Arc<SourceFile>>,
    pub module_display_specifiers: std::collections::HashMap<u64, String>,
    pub display_enclosing_node: Option<Arc<Node>>,
    pub current_file_symbol: Option<Arc<Symbol>>,
    pub scope_stack: Vec<u64>,
    pub function_scope_count: usize,
    pub arrow_function_scope_count: usize,
    pub globals_populated: bool,
    pub break_continue_context_stack: Vec<BreakContinueContext>,
    pub this_type_stack: Vec<Arc<Type>>,
    pub display_target_override: Option<Arc<Type>>,
    pub enclosing_class_stack: Vec<Arc<Node>>,
    pub this_container_stack: Vec<ThisContainerKind>,
    pub ambient_context_depth: usize,
    pub(crate) ambient_statement_reported: std::collections::HashSet<u64>,
    pub namespace_value_depth: u8,
    pub accessor_pair_return_hint: Option<Arc<Type>>,
    pub call_arg_arrow_context: Vec<usize>,
    pub resolving_type_aliases: std::collections::HashSet<*const Symbol>,
    pub alias_resolution_stack: Vec<Arc<Symbol>>,
    pub alias_circular_frames: std::collections::HashSet<*const Symbol>,
    pub alias_circular_reported: std::collections::HashSet<u64>,
    pub resolving_function_like: std::collections::HashSet<u64>,
    pub class_statics_resolution_stack: Vec<u64>,
    pub class_type_resolution_stack: Vec<u64>,
    pub resolving_contextual_calls: std::collections::HashSet<u64>,
    pub logical_rhs_narrowing_frames: Vec<(Arc<Symbol>, Arc<Type>)>,
    pub in_ctor_body_stack: Vec<bool>,
    pub return_type_stack: Vec<Option<Arc<Type>>>,
    pub flow_analysis_disabled: bool,
    pub definite_assignment_check_depth: u32,
    pub flow_invocation_count: i32,
    pub flow_type_cache: HashMap<u64, Arc<Type>>,
    pub flow_node_reachable: HashMap<u64, bool>,
    pub type_instantiation_count: u64,
    pub type_instantiation_limit_reported: bool,
    pub flow_inline_level: u32,
    pub in_static_member_type: bool,
    pub suppress_cannot_find_name_in_type_nodes: u32,
    pub suppress_source_file: Option<u64>,
    pub tracer: Arc<Tracer>,
    pub narrowable_reference_query_stack: Vec<u64>,
    pub merged_symbols: HashMap<u64, u64>,
    pub merged_symbol_targets: HashMap<u64, Arc<tsox_frontend::ast::Symbol>>,
    pub mu: Mutex<()>,
}
