[package]
name = "tsox-tsoptions"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bitflags = "2"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
tsox-core = { workspace = true }
tsox-frontend = { workspace = true }
