use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());

    let libs_source_dir = manifest_dir.join("libs");
    let dest_libs_dir = out_dir.join("bundled_libs");
    fs::create_dir_all(&dest_libs_dir).unwrap();

    let mut entries: Vec<(String, PathBuf)> = Vec::new();
    for entry in fs::read_dir(&libs_source_dir).unwrap().flatten() {
        let path = entry.path();
        if path.extension().and_then(|e| e.to_str()) == Some("ts") {
            let name = path
                .file_name()
                .and_then(|n| n.to_str())
                .unwrap()
                .to_string();
            let dest = dest_libs_dir.join(&name);
            fs::copy(&path, &dest).unwrap();
            entries.push((name, dest));
        }
    }
    entries.sort_by(|a, b| a.0.cmp(&b.0));

    let mut src = String::new();
    src.push_str("/// Bundled `lib.*.d.ts` files, generated by build.rs.\n");
    src.push_str("pub fn bundled_libs() -> &'static [(&'static str, &'static str)] {\n    &[\n");
    for (name, _) in &entries {
        src.push_str(&format!(
            "        (\"{name}\", include_str!(\"bundled_libs/{name}\")),\n"
        ));
    }
    src.push_str("    ]\n}\n");

    fs::write(out_dir.join("bundled_libs.rs"), src).unwrap();
    println!("cargo:rerun-if-changed={}", libs_source_dir.display());
}
